CREATE TABLE hackathon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    data_inicio DATE NOT NULL,
    data_termino DATE NOT NULL,
    max_equipes INTEGER NOT NULL CHECK (max_equipes > 0),
    CONSTRAINT ck_hackathon_datas CHECK (data_termino >= data_inicio)
);
