@startuml Diagrama de Casos de Uso

left to right direction
skinparam packageStyle rectangle
skinparam linetype ortho

actor "Usuário" as Usuario
actor Organizador
actor Participante
actor Jurado
actor Estudante

Organizador -up-|> Usuario
Participante -up-|> Usuario
Jurado -up-|> Usuario

rectangle "Sistema de Hackathons" {
    usecase "UC00\nAutenticar-se" as Login

    usecase "UC01\nCadastrar Hackathon" as UC01
    usecase "UC02\nCadastrar Participante" as UC02
    usecase "UC03\nCriar Equipe" as UC03
    usecase "UC04\nAdicionar Participante\nà Equipe" as UC04
    usecase "UC05\nBuscar Hackathons\nDisponíveis" as UC05

    usecase "UC06\nAvaliar Projeto" as UC06
    usecase "UC07\nConsultar Informações\nde Avaliações" as UC07
    usecase "UC08\nConsultar Classificação\nFinal dos Projetos" as UC08
}

Usuario --> Login
Usuario --> UC08

Organizador --> UC01
Organizador --> UC07

Estudante --> UC02
Participante --> UC03
Participante --> UC04
Participante --> UC05

Jurado --> UC06

@enduml